name: unit_test

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: |
            make test
            make e1
            make e2
            make e3
